#ifndef DEFINICOES_SISTEMA_H_INCLUDED
#define DEFINICOES_SISTEMA_H_INCLUDED

#define true 1
#define false 0

#define NUM_ESTADOS 3
#define NUM_EVENTOS 4

// ESTADOS
#define DESCONECTADO 0
#define OPERANDO 1
#define DESPEJO 2

// EVENTOS
#define NENHUM_EVENTO -1
#define CONECTADO 0
#define CONFIGURAR 1
#define HORARIO_INICIO 2
#define HORARIO_FIM 3

// ACOES
#define NENHUMA_ACAO -1
#define A01 0
#define A02 1
#define A03 2

#endif // DEFINICOES_SISTEMA_H_INCLUDED
